# Generated by Django 5.1.1 on 2024-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('nameofevent', models.CharField(max_length=255)),
                ('eventdetails', models.CharField(max_length=1000)),
                ('eventfund', models.CharField(max_length=255)),
            ],
        ),
    ]
