# Generated by Django 5.1.1 on 2024-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventers',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventers',
            name='eventfund',
            field=models.IntegerField(),
        ),
    ]
