# Generated by Django 5.1.1 on 2024-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0002_eventers_joined_date_eventers_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventers',
            name='eventfund',
            field=models.IntegerField(null=True),
        ),
    ]
